### PR TITLE
nocache@2

### LINKED ISSUE #12: Remove `noEtag` option
Tasks:

- remove `depd`
- remove `noEtag` from source
- remove `noEtag` tests
- remove any `options` parsing; it's the only option
- make sure the README doesn't say anything about `noEtag`
- update the master changelog in `helmetjs/helmet`

### LINKED ISSUE #13: Add missing test for Surrogate-Control header
Noticed it was missing!

### PR DESCRIPTION
**Pull request by EvanHahn**
**Seems ready to be merged and released!**

This is the finished `nocache@2.0.0`.

Breaking changes:

- `noEtag` option was removed

Fixes #12.
Fixes #13.

### CODE REVIEW

**Comment by ruhnowg** [comment]
I was wondering, why you are removing the noEtag option?

**Comment by EvanHahn** [comment]
@ruhnowg Express sets ETags of its own, and that option led people to believe that it was removing ETags, when it might not. Happy to whip up an example if you'd like!

**Comment by ruhnowg** [comment]
@EvanHahn when you refer to etags of its own, do you mean the etags that are added by default via the etag argument as described [here](http://expressjs.com/en/api.html)?

**Comment by EvanHahn** [comment]
@ruhnowg Right. And I _believe_ (unless it's changed) that certain Express features like `res.sendFile` send etags pretty aggressively.

**Comment by analog-nico** [comment]
@ruhnowg If you want to remove the etags that a generated by Express you can use:

``` js
var onHeaders = require('on-headers');

onHeaders(res, function () {
    this.removeHeader('ETag');
});
```

`on-headers` provides a hook which is executed at the very end before the response is sent. Only at this point the etag header already exists. A regular middleware couldn't delete it because it is not yet created when the middleware is executed.

**Comment by EvanHahn** [comment]
Exactly. I considered using what @analog-nico recommended but it doesn't feel like it should be part of this middleware.

**Comment by analog-nico** [comment]
I agree, in a sense the etag mechanism is completely different from other caching mechanisms.

Those that `nocache` blocks are primarily in the hand of browsers/CDNs etc. They decide if a cache entry is still good or needs to be refetched. And since they may make a bad decision I prefer to use `nocache` to make sure the user sees the latest image etc. on the webpage.

ETags on the other hand are always checked against the server:

1. The client requests a resource for the first time
2. The server responds with the resource along with an etag
3. The client requests the resource for the second time and send the etag along to the server
4. The server decides if the etag is good or not
    - If the etag is good the server responds with a 304 and the client uses the cached resource
    - If the etag is bad the server responds with the up-to-date resource and the client updates its cache

So since it is in the hands of the server to decide if the cache can be used or not – so no bad decisions can happen – it is usually a good idea to keep ETags turned on. If you, however, want to turn ETags off then just turning them off for all resources – including all static resources you serve – would make you loose all the benefits that really have no drawbacks.

Or did I miss any drawbacks ETags might have?

**Comment by EvanHahn** [comment]
That's been my understanding.

The main drawback of etags I see is performance. There can be slowness (1) calculating them (2) sending/receiving them (3) validating them.

In any case, this module seems like it doesn't need the `noEtags` option.

**Comment by analog-nico** [comment]
Oh yes, indeed. My solution above wouldn't solve (1) because the etags are still calculated and just deleted right before the response is sent.

**Comment by ruhnowg** [comment]
One other problem with express automatically adding etags is that it will cause the content of the response to be cached on the user's machine when maybe you do not want it to.  For example if a route handles sensitive information such as social security numbers you probably don't want that cached for any reason.

I believe once you've created you express app simply doing:

```
app.disable('etags')
```

is sufficient to prevent express from automatically adding etags, but I don't think this is an option for nocache since nocache is a middleware.

Thanks for all your responses!

**Pull request merged**
