### PR TITLE
add 'private' to Cache-Control header

### LINKED ISSUE #2: Cache-Control should include private
Seems like the `Cache-Control` header should include `private`.  Per [RFC2616 14.9.1](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html):

> **private**: Indicates that all or part of the response message is intended for a single user and MUST NOT be cached by a shared cache. This allows an origin server to state that the specified parts of the response are intended for only one user and are not a valid response for requests by other users. A private (non-shared) cache MAY cache the response.

Caches like [varnish](https://www.varnish-cache.org/) will happily cache the current response, but would not if `private` were included.

Thoughts?

### PR DESCRIPTION
**Pull request by makebbekus**
fixes #2

### CODE REVIEW

**Comment by EvanHahn** [comment]
Thanks! Will push a new version now.

**Comment by makebbekus** [comment]
Cool, thanks Evan!

**Comment by EvanHahn** [comment]
@makebbekus I'm planning on starting a list of contributors (probably just a big list of bullet points) and I'd like to put you on the list. How should I credit you?

**Comment by makebbekus** [comment]
Thanks @EvanHahn! My github account is great.

**Pull request merged**
